# Generated by Django 4.1.7 on 2023-02-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='name',
        ),
        migrations.AddField(
            model_name='students',
            name='student',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
