# Generated by Django 4.1.7 on 2023-02-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_students_name_students_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='student',
        ),
        migrations.AddField(
            model_name='students',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='second_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
