# Generated by Django 4.1.7 on 2023-02-27 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='groups_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.groups'),
        ),
        migrations.AlterField(
            model_name='score',
            name='students_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.students'),
        ),
        migrations.AlterField(
            model_name='score',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='api.subjects'),
        ),
    ]
